source 'https://github.com/LovePlayModule/Podspec.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Mediator_Example' do
  pod 'Mediator', :path => '../'
#  pod 'Mediator', :git => 'https://github.com/LovePlayModule/Mediator.git'
  target 'Mediator_Tests' do
    inherit! :search_paths

    
  end
end
